Add announcement API usecase
CCIP-App/CCIP-Serverless pull request #18
Opened 2023-08-30 09:24 UTC by dannyh79

#5

This adds announcement API usecase.

### Todos
- [x] Core: Add announcement domain entity #17
- [x] API: Add repo #17
- [x] API: Add usecase
- [ ] Worker: Add endpoint
- [ ] E2E test: Add scenario

2023-08-30 09:41 UTC, elct9620 requested changes

2023-08-30 09:41 UTC, elct9620 commented on api/schema/announcement.ts
> +export type Announcement = AnnouncementEntity
這裡不該用 Domain Model 來定義，這會造成多餘的依賴，也不符合 Layered Architecture 要求（理論上 Presentation Layer 應該只知道 Application Layer 的資訊）

2023-08-30 09:41 UTC, elct9620 commented on api/usecase/announcementInfo.ts
> +    const results = await this.announcementRepository.listAll()
Use Case 不應該直接把 Domain Model 回傳

2023-08-30 11:44 UTC, dannyh79 commented on api/schema/announcement.ts
> +export type Announcement = AnnouncementEntity
70bfbf7

2023-08-30 11:54 UTC, dannyh79 commented on api/usecase/announcementInfo.ts
> +    const results = await this.announcementRepository.listAll()
是指將 returned results 轉成 plain objects 嗎？目前在 usecase 沒有需要經過特別處理資料。

2023-08-30 14:33 UTC, elct9620 commented on api/usecase/announcementInfo.ts
> +    const results = await this.announcementRepository.listAll()
還是要做，因為定義上不一樣

從 Repository 拿出來的是 Domain Model (Entity) 直接傳到 UseCase 以外就變成 Presenter 對 Domain Model 依賴

2023-08-31 03:30 UTC, dannyh79 commented on api/usecase/announcementInfo.ts
> +    const results = await this.announcementRepository.listAll()
d6515bd

2023-08-31 03:45 UTC, elct9620 approved these changes

2023-08-31 03:45 UTC, merged

2023-08-31 03:46 UTC, elct9620 commented
基本上應該要先把 E2E 的測試寫完後再做實作，才不會出現 DB 設計限制 API / UseCase 的狀況

2023-08-31 03:48 UTC, dannyh79 commented
> 基本上應該要先把 E2E 的測試寫完後再做實作，才不會出現 DB 設計限制 API / UseCase 的狀況

忘記有 `@wip` 可以用了。下次會先 commit 測試 as `@wip` 。

2023-08-31 03:55 UTC, elct9620 commented
如果有切開的話，應該不太會用到 `@wip` 

1. System Analysis
2. API Interface - `api/schema`
3. Add E2E testing
4. Implement API endpoint with fix response
5. (PR)
6. Implement API use case with fix result
7. (PR)
8. Implement/Update related entity
9. (PR)