Implement usecase AnnouncementInfo#create
CCIP-App/CCIP-Serverless pull request #30
Opened 2023-09-15 09:40 UTC by dannyh79

#5 

This implements the usecase method and its D1 repo.

2023-09-15 11:45 UTC, elct9620 requested changes

2023-09-15 11:45 UTC, elct9620 commented on api/repository/announcements.ts
> +  async create(params: CreateAnnouncementParams): Promise<void> {
這裡給進去的應該要是一個 Entity

2023-09-15 11:45 UTC, elct9620 commented on api/usecase/announcementInfo.ts
> +  public async create(params: CreateAnnouncementParams): Promise<void> {
~~命名應該統一一下用 `Request` 和 `Response` 對應~~

UseCase 不應該吃到 API Schema 的定義

2023-09-15 11:45 UTC, elct9620 commented on api/usecase/repository.ts
> +  create(params: Omit<Announcement, 'id'> & { roles: string[] }): Promise<void>
這邊的 Signature 跟 Repository 對不起來

2023-09-15 11:45 UTC, elct9620 commented on worker/controller/announcement.ts
> +    const params = await new Response(request.body).json<AnnouncementPayload>()
這裡為什麼會是 `new Response(request.body)`？

2023-09-17 04:28 UTC, dannyh79 commented on worker/controller/announcement.ts
> +    const params = await new Response(request.body).json<AnnouncementPayload>()
感謝提醒，將改為以下。此應之前看 itty-router 文件測試時不小心留下的 code 。
```diff
   async createAnnouncement(request: AnnouncementRequest) {
-    const params = await new Response(request.body).json<AnnouncementPayload>()
+    const params = await request.json<AnnouncementPayload>()
```

2023-09-17 05:02 UTC, dannyh79 commented on worker/controller/announcement.ts
> +    const params = await new Response(request.body).json<AnnouncementPayload>()
b2316a2

2023-09-17 05:03 UTC, dannyh79 commented on api/repository/announcements.ts
> +  async create(params: CreateAnnouncementParams): Promise<void> {
a920fbb

2023-09-17 05:03 UTC, dannyh79 commented on api/usecase/announcementInfo.ts
> +  public async create(params: CreateAnnouncementParams): Promise<void> {
33bfb6a

2023-09-17 05:05 UTC, dannyh79 commented on api/usecase/repository.ts
> +  create(params: Omit<Announcement, 'id'> & { roles: string[] }): Promise<void>
已於 a920fbb 修正 D1AnnouncementRepository#create 的 signature 。

2023-09-17 06:48 UTC, elct9620 commented on api/usecase/announcementInfo.ts
> +type CreateAnnouncementRequest = Omit<Announcement, 'id' | 'announcedAt'> & {
`Omit<Announcement, 'id' | 'announcedAt'>` Entity 的 Attribute 不應該是 Use Case 參數的資訊

2023-09-17 06:49 UTC, elct9620 commented on api/repository/announcements.ts
> +    params: Omit<Announcement, 'id'> & {
Repository 收到的要是 Entity

2023-09-27 10:49 UTC, closed without merging