Use listAnnouncementsByToken query in AnnouncementController
CCIP-App/CCIP-Serverless pull request #32
Opened 2023-09-26 04:45 UTC by dannyh79

This adds query `ListAnnouncementsByToken` to `AnnouncementController`. Current (old) usecase impl will be removed in the following PR.

2023-09-26 07:59 UTC, elct9620 requested changes

2023-09-26 07:59 UTC, elct9620 commented on api/projection/listAnnouncementsByAttendee.ts
> +    if (!role) {
沒有 Role 的話 `results` 應該會直接回傳空陣列？

2023-09-26 07:59 UTC, elct9620 commented on api/projection/listAnnouncementsByAttendee.ts
> +const toAnnouncement = (data: AnnouncementSchema): Announcement => ({
這邊要 `new Announcement(...)` 才合理

2023-09-27 04:02 UTC, dannyh79 commented on api/projection/listAnnouncementsByAttendee.ts
> +    if (!role) {
感謝建議。將改為沒有 `role` query input 時回傳空陣列（原實作 API query 沒 attendee token 時預設回傳給 roles 含 "audience" 的 announcement 目前是放在於 query 裡）。

2023-09-27 04:04 UTC, dannyh79 commented on api/projection/listAnnouncementsByAttendee.ts
> +const toAnnouncement = (data: AnnouncementSchema): Announcement => ({
2afe578

2023-09-27 04:04 UTC, dannyh79 commented on api/projection/listAnnouncementsByAttendee.ts
> +    if (!role) {
1678055

2023-09-27 04:39 UTC, merged