Replace AnnouncementInfo by InitializeAnnouncement
CCIP-App/CCIP-Serverless pull request #35
Opened 2023-09-27 10:28 UTC by dannyh79

This makes what was in `AnnouncementInfo` conforms interface `Command`.

2023-09-27 15:33 UTC, elct9620 requested changes

2023-09-27 18:16 UTC, dannyh79 commented on api/command/initializeAnnouncement.ts
> +    await this.announcementRepository.create(params)
> Repository 操作的對象是 Entity 不是 DTO

請見 #36 。因為再加上改 entity commit 的話 PR 的更動會太多。

2023-09-27 18:17 UTC, dannyh79 commented on api/command/initializeAnnouncement.ts
> +    await this.announcementRepository.create(params)
> Repository 不會有 create 的情況

Refactor 預計於後安排。目前先沿用現有的 code 。

2023-09-28 03:41 UTC, elct9620 commented on api/command/initializeAnnouncement.ts
> +    await this.announcementRepository.create(params)
下次可以調整一下修改的順序讓需要調整的部分先改完

2023-09-28 07:34 UTC, dannyh79 commented on worker/controller/announcement.ts
> +const toCreateAnnouncementParams = (
轉成合乎 create announcement 用的 params 。

稍後將更正 request params `role` 的型別，剛剛發現是 cucumber mock steps 等處實作有疏漏。

2023-09-28 07:49 UTC, dannyh79 commented on api/command/initializeAnnouncement.ts
> +export class InitializeAnnouncement implements Command<InitializeAnnouncementInput, void> {
f822a6d

2023-09-28 07:49 UTC, dannyh79 commented on worker/controller/announcement.ts
> +const toCreateAnnouncementParams = (
8ff7515 & 6d8aea1

2023-09-28 09:23 UTC, elct9620 requested changes

2023-09-28 09:23 UTC, elct9620 commented on worker/controller/announcement.ts
> +const toCreateAnnouncementParams = (
`CreateAnnouncment` 是 Command 這邊轉換的結果要是 `CreateAnnouncementInput` 為什麼會是自己的型別？

2023-09-28 12:27 UTC, dannyh79 commented on worker/controller/announcement.ts
> +const toCreateAnnouncementParams = (
感謝提醒。這邊閱讀了一下[相關文章](https://martinfowler.com/bliki/CQRS.html)後得知 controller 這層要用到 command/query 的 interface 。

2023-09-28 12:31 UTC, dannyh79 commented on worker/controller/announcement.ts
> +const toCreateAnnouncementParams = (
5a6b655

2023-09-28 12:48 UTC, elct9620 commented on worker/controller/announcement.ts
> +const toCreateAnnouncementParams = (
DDD 裏面：Controller -> UseCase -> Entity
CQRS 對應：Controller -> Command/Query (UseCase) -> Entity

https://github.com/CCIP-App/CCIP-Serverless/blob/a665ab3238e6a8cb187f0d1a13f57bb6828ad1c3/src/core/usecase.ts#L1-L6

2023-09-28 12:49 UTC, elct9620 commented on worker/controller/announcement.ts
> +    messageEn: typeof data.msg_en === 'string' ? data.msg_en : null,
資料輸入型別錯誤拋 Error 比較合理，原系統沒有這個行為先無視

2023-09-28 12:50 UTC, merged